[project]
name = "timebank"
description = "Time-based skill exchange"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.timebank]
path = "contracts/timebank.clar"

[repl.analysis]
passes = ["check_checker"]
